version: "3"

networks:
  siksa-clock-web:
    driver: overlay
    external: true
services:
  # Back End
  back_end_mvp:
    build: back-end/mvp
    ports:
      - 7777:7777
    networks:
      - siksa-clock-web

  siksa_clock_nginx:
    build: infra
    ports:
      - 80:80
      - 443:443
    networks:
      - siksa-clock-web
    

  # Front End
