version: "3"

networks:
  siksa-clock-web:
    external: true

services:
  # Back End
  mealplain_api:
    build: back-end/mealplain_api
    ports:
      - 7777:7777
    networks:
      - siksa-clock-web

  siksa_clock_nginx:
    build: infra
    ports:
      - 80:80
      - 443:443
    networks:
      - siksa-clock-web
    

  # Front End
