version: "3"

networks:
  siksa-clock-web:
    external: true

services:
  mealplan_api:
    build:
      context: .
      dockerfile: back-end/mealplan_api/
    ports:
      - "7777:7777"
    networks:
      - siksa-clock-web

  siksa_clock_nginx:
    build:
      context: .
      dockerfile: infra/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - siksa-clock-web
    depends_on:
      - mealplan_api