version: "3"

networks:
  siksa-clock:
    driver: bridge
services:
  # Back End
  back-end-mvp:
    container_name: siksa_clock_mvp
    build: back-end/mvp
    ports:
      - 80:80

  nginx:
    container_name: siksa_clock_nginx
    build: infla
    ports:
      - 80:80
      - 443:443
    
    

  # Front End
